/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  sepolia: {
    PaymentProcessor: {
      address:
        "0x7188039bb062bfa53b24c7d529301c9f0495abe1ef660788f4a12d86394e508",
      abi: [
        {
          type: "impl",
          name: "PaymentProcessorImpl",
          interface_name: "contracts::payment_processor::IPaymentProcessor",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::payment_processor::IPaymentProcessor",
          items: [
            {
              type: "function",
              name: "process_payment",
              inputs: [
                {
                  name: "merchant",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_stats",
              inputs: [],
              outputs: [
                {
                  type: "(core::integer::u256, core::integer::u256)",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::payment_processor::PaymentProcessor::PaymentProcessed",
          kind: "struct",
          members: [
            {
              name: "from",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "to",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::payment_processor::PaymentProcessor::Event",
          kind: "enum",
          variants: [
            {
              name: "PaymentProcessed",
              type: "contracts::payment_processor::PaymentProcessor::PaymentProcessed",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x3de306cfb21a9720fc4815fa449f21c6394265196955f8563bcf12649ac61e0",
    },
    RemesaVault: {
      address:
        "0x6d919b7463697668ca357e40e33c488d28f84eed55914c98a6a5bfc7feff9a0",
      abi: [
        {
          type: "impl",
          name: "RemesaVaultImpl",
          interface_name: "contracts::remesa_vault::IRemesaVault",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::remesa_vault::IRemesaVault",
          items: [
            {
              type: "function",
              name: "initiate_transfer",
              inputs: [
                {
                  name: "to",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "complete_transfer",
              inputs: [
                {
                  name: "to",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_platform_stats",
              inputs: [],
              outputs: [
                {
                  type: "(core::integer::u256, core::integer::u256)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "update_platform_fee",
              inputs: [
                {
                  name: "new_fee_bps",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "platform_fee_bps",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::remesa_vault::RemesaVault::TransferInitiated",
          kind: "struct",
          members: [
            {
              name: "from",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "to",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::remesa_vault::RemesaVault::TransferCompleted",
          kind: "struct",
          members: [
            {
              name: "from",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "to",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "fee_amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::remesa_vault::RemesaVault::Event",
          kind: "enum",
          variants: [
            {
              name: "TransferInitiated",
              type: "contracts::remesa_vault::RemesaVault::TransferInitiated",
              kind: "nested",
            },
            {
              name: "TransferCompleted",
              type: "contracts::remesa_vault::RemesaVault::TransferCompleted",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x6f8d5097737f700df772954853bdb2190eb9841b7ad74b93d06793fe81f5a1b",
    },
    TandaSavings: {
      address:
        "0x6efe48d74ebdea9c5b797b399808a0f3770346cf7cdd6e240a06be5ea06e482",
      abi: [
        {
          type: "impl",
          name: "TandaSavingsImpl",
          interface_name: "contracts::tanda_savings::ITandaSavings",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::tanda_savings::ITandaSavings",
          items: [
            {
              type: "function",
              name: "create_tanda",
              inputs: [
                {
                  name: "name",
                  type: "core::felt252",
                },
                {
                  name: "contribution_amount",
                  type: "core::integer::u256",
                },
                {
                  name: "max_members",
                  type: "core::integer::u256",
                },
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "join_tanda",
              inputs: [
                {
                  name: "tanda_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "contribute",
              inputs: [
                {
                  name: "tanda_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "execute_payout",
              inputs: [
                {
                  name: "tanda_id",
                  type: "core::integer::u256",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_tanda_count",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::tanda_savings::TandaSavings::TandaCreated",
          kind: "struct",
          members: [
            {
              name: "tanda_id",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "name",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "contribution_amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::tanda_savings::TandaSavings::MemberJoined",
          kind: "struct",
          members: [
            {
              name: "tanda_id",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "member",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::tanda_savings::TandaSavings::ContributionMade",
          kind: "struct",
          members: [
            {
              name: "tanda_id",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "member",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::tanda_savings::TandaSavings::PayoutExecuted",
          kind: "struct",
          members: [
            {
              name: "tanda_id",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::tanda_savings::TandaSavings::Event",
          kind: "enum",
          variants: [
            {
              name: "TandaCreated",
              type: "contracts::tanda_savings::TandaSavings::TandaCreated",
              kind: "nested",
            },
            {
              name: "MemberJoined",
              type: "contracts::tanda_savings::TandaSavings::MemberJoined",
              kind: "nested",
            },
            {
              name: "ContributionMade",
              type: "contracts::tanda_savings::TandaSavings::ContributionMade",
              kind: "nested",
            },
            {
              name: "PayoutExecuted",
              type: "contracts::tanda_savings::TandaSavings::PayoutExecuted",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x26a3f687ad2e66e5c3ad0f5c0e0ec05427d4bd0fc5ddeaf051f5853e2c24949",
    },
  },
} as const;

export default deployedContracts;
