[package]
name = "starkpays_contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.3.0"

[[target.starknet-contract]]
sierra = true
casm = true

[profile.dev]
opt-level = 3
overflow-checks = true

[profile.release]
opt-level = 3
overflow-checks = true